name: Push on tagged release

on:
  release:
    types: [released]

env:
  IMAGE_NAME: godot
  GODOT_VERSION: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push regular Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.GODOT_VERSION }}
          build-args:
            GODOT_VERSION=${{ env.GODOT_VERSION }}
